export const DEFAULT_STAIR = {
  height: 108,
  run: 144,
  width: 48,
  steps: 6,
  tubeSize: '2x2',
  railingEnabled: true,
  handrailHeight: 36,
  pinOpening: 3.875,
  postSpacing: 48,
  railingRunMode: 'matchStair',
  manualRailingRun: 144,
  bottomLandingEnabled: true,
  bottomLandingLength: 36,
  topLandingEnabled: true,
  topLandingLength: 36,
  topLandingWidth: 48,
  bottomRailEnabled: false,
  bottomRailHeight: 1,
  middleRailEnabled: false,
  middleRailHeights: [18],
  railingColorMode: 'color',
  railingSideMode: 'left',
  railLowerExtensionIn: 0,
  railUpperExtensionIn: 0,
  post1HeightIn: 36,
  post1Section: '2 x 2',
  post1Thickness: '1.8',
  post2HeightIn: 36,
  post2Section: '2 x 2',
  post2Thickness: '1.8',
  compactTopHandrailEnabled: true,
  handrailSection: '2 x 1',
  compactBottomChannelEnabled: true,
  bottomChannelSection: '2 x 1',
  infillType: 'none',
  picketVerticalSection: '1 x 1',
  picketVerticalThickness: '1.8',
  picketHorizontalSection: '1 x 1',
  picketHorizontalThickness: '1.8',
  cableSize: '1/8',
  cableFinish: 'Black',
  verticalPicketThicknessIn: 1,
  horizontalPicketThicknessIn: 1,
  horizontalCableDiameterIn: 0.125,
};

export const DEFAULT_PROJECT = {
  name: '',
  client: '',
};
