export const DEFAULT_STAIR = {
  height: 108,
  run: 144,
  width: 48,
  steps: 6,
  tubeSize: '2x2',
  railingEnabled: true,
  handrailHeight: 36,
  pinOpening: 3.875,
  postSpacing: 48,
  railingRunMode: 'matchStair',
  manualRailingRun: 144,
  bottomLandingEnabled: true,
  bottomLandingLength: 36,
  topLandingEnabled: true,
  topLandingLength: 36,
  topLandingWidth: 48,
  bottomRailEnabled: false,
  bottomRailHeight: 1,
  middleRailEnabled: false,
  middleRailHeights: [18],
  railingColorMode: 'color',
  railingSideMode: 'left',
  railLowerExtensionIn: 0,
  railUpperExtensionIn: 0,
  infillType: 'none',
  verticalPicketThicknessIn: 1,
  horizontalPicketThicknessIn: 1,
  horizontalCableDiameterIn: 0.125,
};

export const DEFAULT_PROJECT = {
  name: '',
  client: '',
};
